#!/bin/bash

# get system log to attachment
curl -su user:pass https://pro.jamf.training:8443/08/JSSResource/fileuploads/computers/id/3000 -F "name=@/var/log/system.log filename=system-`date`.log" -X POST

jamf displayMessage -message "Please restart your computer"

sudo jamf policy -id 1
