#!/bin/bash

# ask user for serial number
serialNumber=$(osascript -e 'text returned of(display dialog "Please type in your serial number" default answer "" buttons {"OK"} default button 1)')

curl -su jamfadmin:jamf1234 -H "accept: text/xml" https://pro.jamf.training:8443/08/JSSResource/mobiledevices/serialnumber/$serialNumber -X GET | xmllint --xpath '/mobile_device/location/username/text()' -

